nome = str(input('Digite o seu nome: '))
print('Analisando seu nome...')
print('Seu nome em maiusculas é {} ' .format(nome.upper()))
print('Seu nome em minusculas é {} ' .format(nome.lower()))
print('Seu nome tem ao todo {} letras ' .format(len(nome)-nome.count(' ')))
print('Seu primeiro nome tem {} letras' .format(nome.find(' ')))
